
CREATE DATABASE USER;
USE USER;

CREATE TABLE USERS(
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(150) NOT NULL,
    PhoneNumber VARCHAR(10) NOT NULL UNIQUE,
    Age INT CHECK (Age >= 18 AND Age <= 100),
    Gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PASSCODE VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM USERS;
